# Generated by Django 5.1.1 on 2024-09-13 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="uuid",
            field=models.UUIDField(
                auto_created=True, default=uuid.uuid4, editable=False
            ),
        ),
    ]
