# Generated by Django 5.1.1 on 2024-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_skill_delete_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="background",
            field=models.ImageField(default=None, upload_to="backgrounds"),
        ),
    ]
