# Generated by Django 5.1.1 on 2024-09-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_follow_uuid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Follow",
        ),
    ]
